### PR TITLE
add empty callback if not given with options

### PR DESCRIPTION
**Pull request by coolchip**
Hey,
thank you very much for your node module. I like it very much, but it has an error. If sending a command it failed at 'res.on('data', self.callback);', because self.callback is not set. So I add an empty function, when it is not set. It would be very, very greate, if you add this to your module.

### CODE REVIEW

**Comment by samuelmatis** [comment]
Hi, thank you very much for this bug report and correction.

**Comment by coolchip** [comment]
I forgot... Can you please `npm version patch && npm publish`? Would be very, very nice... ;)

**Comment by samuelmatis** [comment]
Hi, i've published a new version to npm. Thanks for notice. Happy new year!

**Comment by coolchip** [comment]
You are the best. 
Happy new year.

**Pull request merged**
